# Generated by Django 3.2.9 on 2022-04-16 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_product_sale'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='tick',
            field=models.BooleanField(default=False),
        ),
    ]
